
export const userType = {
    REGISTER_DATA: "REGISTER_DATA",
    TOKEN: "TOKEN",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    IS_LOGIN: "IS_LOGIN",
    CLEAR_PASSWORD: "CLEAR_PASSWORD",
    USER_DATA: "USER_DATA",
};

export const globalType = {
    IS_LOADING: "IS_LOADING",
    ALLERT: "ALLERT",
};

export const foodsType = {
    BANNER: "BANNER",
    BANNER_LOADING: "BANNER_LOADING",
    NEW_TASTE: "NEW_TASTE",
    NEW_TASTE_LOADING: "NEW_TASTE_LOADING",
    POPULAR: "POPULAR",
    POPULAR_LOADING: "POPULAR_LOADING",
    RECOMMENDED: "RECOMMENDED",
    RECOMMENDED_LOADING: "RECOMMENDED_LOADING",
}